# Generated by Django 5.2.7 on 2025-10-18 11:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.IntegerField(default=10)),
                ('category', models.CharField(choices=[('CAKE', 'Cakes'), ('DRINK', 'Soft Drinks')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['product_id'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('money_inserted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_returned', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_after', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='MoneyInserted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.IntegerField()),
                ('count', models.IntegerField(default=1)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_details', to='shop.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeReturned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.IntegerField()),
                ('count', models.IntegerField(default=1)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_details', to='shop.transaction')),
            ],
        ),
    ]
