# Generated by Django 5.2.7 on 2025-10-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInventoryLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=20)),
                ('quantity_before', models.IntegerField()),
                ('quantity_purchased', models.IntegerField()),
                ('quantity_left', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'product_inventory_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='moneyinserted',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('snack', 'Snack'), ('drink', 'Soft Drink')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.DeleteModel(
            name='ChangeReturned',
        ),
        migrations.DeleteModel(
            name='MoneyInserted',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
