# Generated by Django 5.2.7 on 2025-10-22 07:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productinventorylog_remove_moneyinserted_transaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeReturned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.IntegerField()),
                ('count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MoneyInserted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.IntegerField()),
                ('count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('money_inserted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_returned', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_after', models.IntegerField()),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.DeleteModel(
            name='ProductInventoryLog',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_id']},
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CAKE', 'Cakes'), ('DRINK', 'Soft Drinks')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
        migrations.AddField(
            model_name='transaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.AddField(
            model_name='moneyinserted',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_details', to='shop.transaction'),
        ),
        migrations.AddField(
            model_name='changereturned',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_details', to='shop.transaction'),
        ),
    ]
